# Site settings
title: jsnotiftray
description: >
  A simple JavaScript notification in tray format
baseurl: "/jsnotiftray" # the subpath of your site, e.g. /blog/
url: "gh-pages" # the base hostname & protocol for your site
github_username:  kylehuff

# Build settings
markdown: kramdown
include:
  - .nojekyll
